import type { Exercise } from "@/types";

export const EXERCISES: Exercise[] = [
  // ===== CHEST =====
  {
    id: "ex-001",
    nameVi: "Đẩy ngực thanh đòn",
    nameEn: "Barbell Bench Press",
    slug: "day-nguc-thanh-don",
    description:
      "Bài tập compound cơ bản nhất cho ngực, đồng thời kích hoạt vai trước và tay sau.",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    goalTags: ["muscle_gain", "strength"],
    instructions: [
      "Nằm trên ghế phẳng, mắt nhìn thẳng lên thanh đòn.",
      "Hai tay rộng hơn vai một chút, nắm thanh chắc.",
      "Hạ thanh xuống ngực kiểm soát trong 2 giây.",
      "Đẩy thanh lên thẳng tay, không khóa khuỷu cứng.",
    ],
    commonMistakes: [
      "Bung lưng quá cao gây áp lực cột sống.",
      "Đẩy nhanh xuống, mất kiểm soát ngực.",
      "Khuỷu tay choãi ngang 90° gây hại vai.",
    ],
    tips: [
      "Giữ bả vai ép xuống ghế suốt động tác.",
      "Hít vào khi hạ, thở ra khi đẩy lên.",
    ],
    alternativeSlugs: ["day-nguc-dumbbell"],
  },
  {
    id: "ex-002",
    nameVi: "Đẩy ngực dumbbell",
    nameEn: "Dumbbell Bench Press",
    slug: "day-nguc-dumbbell",
    description:
      "Phiên bản tự do hơn của đẩy ngực, cho phép biên độ rộng và cân bằng hai bên.",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    goalTags: ["muscle_gain", "toning"],
    instructions: [
      "Nằm phẳng, mỗi tay một dumbbell ngang ngực.",
      "Đẩy lên đỉnh, hai dumbbell gần chạm nhau.",
      "Hạ chậm xuống tới khi cảm thấy căng ngực.",
    ],
    commonMistakes: [
      "Hạ tay quá nhanh.",
      "Khoá khuỷu khi đẩy lên gây sốc khớp.",
    ],
    tips: ["Hơi nghiêng cổ tay vào trong khi đẩy lên để siết ngực hơn."],
  },
  {
    id: "ex-003",
    nameVi: "Hít đất",
    nameEn: "Push Up",
    slug: "hit-dat",
    description:
      "Bài bodyweight kinh điển cho ngực, tay sau và core. Phù hợp người mới.",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    goalTags: ["weight_loss", "toning", "muscle_gain"],
    instructions: [
      "Chống tay rộng hơn vai, người thẳng từ vai đến gót.",
      "Hạ thân xuống đến khi ngực gần chạm sàn.",
      "Đẩy lên về vị trí ban đầu.",
    ],
    commonMistakes: [
      "Hông võng xuống do core yếu.",
      "Khuỷu tay choãi ngang 90°.",
    ],
    tips: [
      "Người mới có thể hít đất với đầu gối chạm sàn.",
      "Siết mông và bụng để cơ thể thành đường thẳng.",
    ],
  },
  {
    id: "ex-004",
    nameVi: "Dang ngực dumbbell",
    nameEn: "Dumbbell Fly",
    slug: "dang-nguc-dumbbell",
    description: "Isolation cho ngực, kéo căng và siết ngực ở biên độ rộng.",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    goalTags: ["toning", "muscle_gain"],
    instructions: [
      "Nằm phẳng, hai tay cầm dumbbell mở rộng sang hai bên.",
      "Hơi cong khuỷu, hạ xuống đến khi ngực căng.",
      "Đưa dumbbell lên đỉnh theo cung tròn.",
    ],
    commonMistakes: ["Cánh tay quá thẳng dễ chấn thương khuỷu."],
    tips: ["Dùng tạ nhẹ, tập trung cảm giác căng ở ngực."],
  },

  // ===== BACK =====
  {
    id: "ex-005",
    nameVi: "Kéo xà",
    nameEn: "Pull Up",
    slug: "keo-xa",
    description: "Bài compound cho lưng và tay trước, đo lường sức kéo bản thân.",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "core"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    goalTags: ["muscle_gain", "strength"],
    instructions: [
      "Nắm xà rộng hơn vai, lòng bàn tay hướng ra.",
      "Kéo người lên đến khi cằm vượt xà.",
      "Hạ xuống kiểm soát, không buông tay.",
    ],
    commonMistakes: [
      "Đu người để lấy đà.",
      "Không kéo tới đỉnh, biên độ ngắn.",
    ],
    tips: [
      "Người mới dùng dây kháng lực hỗ trợ.",
      "Siết lưng, ép xương bả vai khi kéo.",
    ],
  },
  {
    id: "ex-006",
    nameVi: "Kéo cáp ngồi",
    nameEn: "Seated Cable Row",
    slug: "keo-cap-ngoi",
    description: "Bài compound an toàn cho lưng giữa và lưng xô.",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable", "machine"],
    difficulty: "beginner",
    goalTags: ["muscle_gain", "toning"],
    instructions: [
      "Ngồi thẳng lưng, chân chống vào đệm.",
      "Kéo cáp về phía bụng, ép xương bả vai.",
      "Thả ra chậm về vị trí ban đầu.",
    ],
    commonMistakes: [
      "Ngả người ra sau lấy đà.",
      "Khóa khuỷu tay quá thẳng khi thả.",
    ],
    tips: ["Tưởng tượng kéo bằng khuỷu tay, không bằng bàn tay."],
  },
  {
    id: "ex-007",
    nameVi: "Lat pulldown",
    nameEn: "Lat Pulldown",
    slug: "lat-pulldown",
    description: "Phiên bản máy của kéo xà, phù hợp người mới.",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    equipment: ["machine", "cable"],
    difficulty: "beginner",
    goalTags: ["muscle_gain", "toning"],
    instructions: [
      "Ngồi thẳng, đùi cố định dưới đệm.",
      "Kéo thanh xuống trước ngực, không sau gáy.",
      "Thả lên chậm, giữ căng lưng xô.",
    ],
    commonMistakes: [
      "Kéo thanh sau gáy gây hại vai.",
      "Ngả người ra sau quá nhiều.",
    ],
    tips: ["Hãy nghĩ kéo bằng nách, không bằng tay."],
  },
  {
    id: "ex-008",
    nameVi: "Deadlift",
    nameEn: "Deadlift",
    slug: "deadlift",
    description:
      "Bài compound hàng đầu cho cả lưng, mông và đùi sau. Yêu cầu form chuẩn.",
    primaryMuscles: ["back", "hamstrings", "glutes"],
    secondaryMuscles: ["core", "quads"],
    equipment: ["barbell"],
    difficulty: "advanced",
    goalTags: ["strength", "muscle_gain"],
    instructions: [
      "Đứng chân rộng bằng hông, thanh đòn sát ống chân.",
      "Cúi hông và đầu gối, nắm thanh rộng bằng vai.",
      "Giữ lưng thẳng, đẩy đất nâng thanh lên.",
      "Đứng thẳng, siết mông ở đỉnh.",
    ],
    commonMistakes: [
      "Cong lưng dưới khi nâng.",
      "Mông bay lên trước, lưng ép theo sau.",
    ],
    tips: [
      "Cứ học form với tạ nhẹ trước khi tăng cân nặng.",
      "Hít sâu, siết core trước mỗi rep.",
    ],
  },

  // ===== SHOULDERS =====
  {
    id: "ex-009",
    nameVi: "Đẩy vai dumbbell",
    nameEn: "Dumbbell Shoulder Press",
    slug: "day-vai-dumbbell",
    description: "Compound chính cho vai, đẩy lên trên đầu.",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    goalTags: ["muscle_gain", "strength"],
    instructions: [
      "Ngồi thẳng, hai tay cầm dumbbell ngang vai.",
      "Đẩy thẳng lên trên đầu.",
      "Hạ xuống chậm về vị trí ban đầu.",
    ],
    commonMistakes: ["Bung lưng quá mức.", "Khoá khuỷu cứng ở đỉnh."],
    tips: ["Siết core và mông giữ thẳng lưng."],
  },
  {
    id: "ex-010",
    nameVi: "Dang vai dumbbell",
    nameEn: "Lateral Raise",
    slug: "dang-vai-dumbbell",
    description: "Isolation cho vai giữa, giúp vai rộng hình chữ V.",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    goalTags: ["toning", "muscle_gain"],
    instructions: [
      "Đứng thẳng, hai tay cầm dumbbell bên hông.",
      "Nâng tay sang ngang đến ngang vai.",
      "Hạ xuống chậm.",
    ],
    commonMistakes: ["Dùng đà, vung tạ.", "Nâng tay quá cao quá vai."],
    tips: ["Cầm tạ nhẹ và làm chậm để cảm nhận vai."],
  },
  {
    id: "ex-011",
    nameVi: "Face Pull",
    nameEn: "Face Pull",
    slug: "face-pull",
    description: "Bài thiết yếu cho vai sau và tư thế lưng trên.",
    primaryMuscles: ["shoulders", "back"],
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    goalTags: ["toning", "muscle_gain"],
    instructions: [
      "Cáp ngang mặt, nắm dây hai tay.",
      "Kéo về phía hai bên mặt, khuỷu mở rộng.",
      "Thả về chậm.",
    ],
    commonMistakes: ["Dùng tạ quá nặng."],
    tips: ["Tưởng tượng tách hai tay sang hai bên đầu."],
  },

  // ===== BICEPS =====
  {
    id: "ex-012",
    nameVi: "Cuốn tạ dumbbell",
    nameEn: "Dumbbell Curl",
    slug: "cuon-ta-dumbbell",
    description: "Isolation cơ bản nhất cho tay trước.",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    goalTags: ["muscle_gain", "toning"],
    instructions: [
      "Đứng thẳng, hai tay cầm dumbbell.",
      "Cuốn lên đến khi tạ gần vai.",
      "Hạ xuống chậm.",
    ],
    commonMistakes: ["Đẩy hông và vai để lấy đà."],
    tips: ["Giữ khuỷu cố định sát hông."],
  },
  {
    id: "ex-013",
    nameVi: "Cuốn tạ thanh đòn",
    nameEn: "Barbell Curl",
    slug: "cuon-ta-thanh-don",
    description: "Phiên bản nặng hơn của cuốn tạ.",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    difficulty: "intermediate",
    goalTags: ["muscle_gain", "strength"],
    instructions: [
      "Đứng thẳng, nắm thanh rộng bằng vai.",
      "Cuốn thanh lên đến gần ngực.",
      "Hạ xuống chậm.",
    ],
    commonMistakes: ["Vung thân lấy đà."],
    tips: ["Tốc độ 2 giây lên, 2 giây xuống."],
  },

  // ===== TRICEPS =====
  {
    id: "ex-014",
    nameVi: "Đẩy ngực hẹp",
    nameEn: "Close Grip Bench Press",
    slug: "day-nguc-hep",
    description: "Compound chính cho tay sau, kèm theo ngực.",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    goalTags: ["muscle_gain", "strength"],
    instructions: [
      "Nằm ghế phẳng, hai tay rộng bằng vai.",
      "Hạ thanh xuống chạm dưới ngực.",
      "Đẩy lên thẳng tay.",
    ],
    commonMistakes: ["Tay quá hẹp gây đau cổ tay."],
    tips: ["Khuỷu tay sát thân khi hạ."],
  },
  {
    id: "ex-015",
    nameVi: "Tricep Pushdown cáp",
    nameEn: "Tricep Pushdown",
    slug: "tricep-pushdown",
    description: "Isolation cho tay sau bằng cáp.",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    goalTags: ["muscle_gain", "toning"],
    instructions: [
      "Đứng thẳng đối diện máy cáp, nắm dây.",
      "Đẩy cáp xuống thẳng tay.",
      "Thả lên chậm.",
    ],
    commonMistakes: ["Khuỷu tay không cố định."],
    tips: ["Khuỷu sát thân, chỉ chuyển động cẳng tay."],
  },

  // ===== LEGS =====
  {
    id: "ex-016",
    nameVi: "Squat thanh đòn",
    nameEn: "Barbell Squat",
    slug: "squat-thanh-don",
    description: "Vua bài tập chân, kích hoạt đùi trước, mông và lưng.",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    goalTags: ["muscle_gain", "strength"],
    instructions: [
      "Thanh đòn đặt trên cơ thang, đứng chân rộng bằng vai.",
      "Hạ xuống đến khi đùi song song sàn.",
      "Đẩy đất đứng lên.",
    ],
    commonMistakes: ["Đầu gối đổ vào trong.", "Lưng dưới cong."],
    tips: ["Đầu gối thẳng hàng với mũi chân."],
  },
  {
    id: "ex-017",
    nameVi: "Goblet Squat",
    nameEn: "Goblet Squat",
    slug: "goblet-squat",
    description:
      "Phiên bản cầm dumbbell trước ngực, an toàn và dễ học form cho người mới.",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    goalTags: ["weight_loss", "toning", "muscle_gain"],
    instructions: [
      "Cầm dumbbell trước ngực bằng hai tay.",
      "Squat xuống tới khi đùi song song sàn.",
      "Đẩy đất đứng lên.",
    ],
    commonMistakes: ["Lưng cong khi xuống sâu."],
    tips: ["Khuỷu tay ép vào trong, dùng để đẩy đầu gối ra ngoài."],
  },
  {
    id: "ex-018",
    nameVi: "Lunge dumbbell",
    nameEn: "Dumbbell Lunge",
    slug: "lunge-dumbbell",
    description:
      "Bài đơn chân, làm việc cân bằng và mông. Tốt cho định hình mông và đùi.",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    goalTags: ["weight_loss", "toning"],
    instructions: [
      "Đứng thẳng, hai tay cầm dumbbell.",
      "Bước chân trước, hạ đầu gối sau xuống gần sàn.",
      "Đẩy bằng gót chân trước về vị trí ban đầu.",
    ],
    commonMistakes: ["Đầu gối trước vượt mũi chân quá nhiều."],
    tips: ["Mỗi bước dài bằng một bước thường."],
  },
  {
    id: "ex-019",
    nameVi: "Romanian Deadlift",
    nameEn: "Romanian Deadlift",
    slug: "romanian-deadlift",
    description: "Bài chuyên cho đùi sau và mông.",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back"],
    equipment: ["barbell", "dumbbell"],
    difficulty: "intermediate",
    goalTags: ["muscle_gain", "toning"],
    instructions: [
      "Đứng chân rộng bằng hông, cầm thanh trước đùi.",
      "Đẩy hông ra sau, hạ thanh xuống đến giữa ống chân.",
      "Siết mông đẩy hông ra trước, đứng thẳng.",
    ],
    commonMistakes: ["Cong lưng dưới."],
    tips: ["Đầu gối hơi cong, đẩy hông là chính."],
  },
  {
    id: "ex-020",
    nameVi: "Leg Press máy",
    nameEn: "Leg Press",
    slug: "leg-press",
    description: "Bài compound chân an toàn cho người mới.",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["machine"],
    difficulty: "beginner",
    goalTags: ["muscle_gain", "weight_loss"],
    instructions: [
      "Ngồi đặt chân lên đệm rộng bằng vai.",
      "Hạ tạ xuống đến khi đầu gối ~90°.",
      "Đẩy lên thẳng nhưng không khoá gối.",
    ],
    commonMistakes: ["Khoá gối cứng ở đỉnh."],
    tips: ["Chân càng cao trên đệm càng tác động mông và đùi sau."],
  },
  {
    id: "ex-021",
    nameVi: "Hip Thrust",
    nameEn: "Hip Thrust",
    slug: "hip-thrust",
    description: "Bài tốt nhất cho mông, tăng vòng 3.",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell", "dumbbell"],
    difficulty: "intermediate",
    goalTags: ["toning", "muscle_gain"],
    instructions: [
      "Vai tựa ghế, thanh đòn đặt trên hông.",
      "Đẩy hông lên đến khi thân song song sàn.",
      "Hạ xuống chậm.",
    ],
    commonMistakes: ["Bung lưng dưới ở đỉnh."],
    tips: ["Siết mông mạnh ở đỉnh, giữ 1 giây."],
  },
  {
    id: "ex-022",
    nameVi: "Bulgarian Split Squat",
    nameEn: "Bulgarian Split Squat",
    slug: "bulgarian-split-squat",
    description: "Squat đơn chân nâng cao, kích thích mông và đùi mạnh.",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    goalTags: ["toning", "muscle_gain"],
    instructions: [
      "Một chân đặt trên ghế phía sau.",
      "Squat xuống bằng chân trước.",
      "Đẩy lên về vị trí ban đầu.",
    ],
    commonMistakes: ["Ngả người về trước quá nhiều."],
    tips: ["Tập trung lực ở gót chân trước."],
  },

  // ===== ABS / CORE =====
  {
    id: "ex-023",
    nameVi: "Plank",
    nameEn: "Plank",
    slug: "plank",
    description: "Bài giữ tĩnh cho core, tăng độ vững thân.",
    primaryMuscles: ["abs", "core"],
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    goalTags: ["weight_loss", "toning"],
    instructions: [
      "Chống khuỷu tay và mũi chân, thân thẳng.",
      "Siết bụng và mông, giữ tư thế.",
    ],
    commonMistakes: ["Mông cong cao, hông võng xuống."],
    tips: ["Bắt đầu 20s, tăng dần lên 60s."],
  },
  {
    id: "ex-024",
    nameVi: "Crunch",
    nameEn: "Crunch",
    slug: "crunch",
    description: "Bài cơ bản cho cơ bụng phía trên.",
    primaryMuscles: ["abs"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    goalTags: ["weight_loss", "toning"],
    instructions: [
      "Nằm ngửa, đầu gối cong, hai tay sau gáy.",
      "Nâng vai lên khỏi sàn, siết bụng.",
      "Hạ xuống chậm.",
    ],
    commonMistakes: ["Kéo cổ bằng tay.", "Nâng quá cao thành sit-up."],
    tips: ["Chỉ nâng đến khi xương bả vai rời sàn."],
  },
  {
    id: "ex-025",
    nameVi: "Russian Twist",
    nameEn: "Russian Twist",
    slug: "russian-twist",
    description: "Bài cho cơ bụng chéo, giúp eo thon.",
    primaryMuscles: ["abs", "core"],
    secondaryMuscles: [],
    equipment: ["bodyweight", "dumbbell"],
    difficulty: "beginner",
    goalTags: ["weight_loss", "toning"],
    instructions: [
      "Ngồi, hơi ngả người ra sau, chân nâng nhẹ.",
      "Xoay thân sang trái rồi sang phải.",
    ],
    commonMistakes: ["Xoay bằng tay, không bằng thân."],
    tips: ["Có thể cầm dumbbell để tăng độ khó."],
  },
  {
    id: "ex-026",
    nameVi: "Mountain Climber",
    nameEn: "Mountain Climber",
    slug: "mountain-climber",
    description: "Cardio và core, đốt mỡ và tăng nhịp tim.",
    primaryMuscles: ["abs", "core"],
    secondaryMuscles: ["shoulders", "quads"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    goalTags: ["weight_loss"],
    instructions: [
      "Vào tư thế plank cao.",
      "Đưa đầu gối lần lượt về phía ngực nhanh.",
    ],
    commonMistakes: ["Mông nhổng cao."],
    tips: ["Giữ thân thẳng, di chuyển nhanh nhưng kiểm soát."],
  },

  // ===== CARDIO / FULL BODY =====
  {
    id: "ex-027",
    nameVi: "Burpees",
    nameEn: "Burpees",
    slug: "burpees",
    description: "Bài full-body đốt mỡ mạnh nhất.",
    primaryMuscles: ["full_body"],
    secondaryMuscles: ["chest", "core", "quads"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    goalTags: ["weight_loss"],
    instructions: [
      "Đứng thẳng, ngồi xuống chống tay.",
      "Bật chân ra sau vào plank.",
      "Hít đất một cái, bật chân về.",
      "Nhảy thẳng lên với hai tay đưa cao.",
    ],
    commonMistakes: ["Mất kiểm soát khi nhảy về."],
    tips: ["Người mới có thể bỏ phần hít đất."],
  },
  {
    id: "ex-028",
    nameVi: "Nhảy dây",
    nameEn: "Jump Rope",
    slug: "nhay-day",
    description: "Cardio dễ làm tại nhà, đốt mỡ và tăng sức bền.",
    primaryMuscles: ["full_body", "calves"],
    secondaryMuscles: ["shoulders", "core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    goalTags: ["weight_loss"],
    instructions: [
      "Cầm dây nhảy hai tay.",
      "Nhảy nhẹ bằng mũi chân, đầu gối hơi cong.",
    ],
    commonMistakes: ["Nhảy quá cao, tốn sức nhanh."],
    tips: ["Bắt đầu 1 phút, nghỉ 30s, lặp 10 hiệp."],
  },
  {
    id: "ex-029",
    nameVi: "Đi bộ máy nghiêng dốc",
    nameEn: "Incline Treadmill Walk",
    slug: "di-bo-may-nghieng-doc",
    description: "Cardio cường độ thấp, đốt mỡ an toàn cho người mới giảm cân.",
    primaryMuscles: ["full_body", "calves", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["machine"],
    difficulty: "beginner",
    goalTags: ["weight_loss"],
    instructions: [
      "Treadmill dốc 8-12%, tốc độ 5-6 km/h.",
      "Đi đều, giữ nhịp tim khoảng 60-70% max.",
    ],
    commonMistakes: ["Bám tay vào thanh ngang."],
    tips: ["Không bám tay để tăng hiệu quả đốt mỡ."],
  },
  {
    id: "ex-030",
    nameVi: "Calf Raise đứng",
    nameEn: "Standing Calf Raise",
    slug: "calf-raise-dung",
    description: "Isolation cho bắp chuối, tăng kích thước và độ bền.",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["bodyweight", "dumbbell"],
    difficulty: "beginner",
    goalTags: ["muscle_gain", "toning"],
    instructions: [
      "Đứng thẳng, kiễng gót lên cao nhất có thể.",
      "Hạ xuống chậm.",
    ],
    commonMistakes: ["Đung đưa thân lấy đà."],
    tips: ["Có thể đứng trên bậc thang để biên độ rộng hơn."],
  },
];

export function getExerciseBySlug(slug: string): Exercise | undefined {
  return EXERCISES.find((e) => e.slug === slug);
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISES.filter(
    (e) =>
      e.primaryMuscles.includes(muscle as never) ||
      e.secondaryMuscles.includes(muscle as never),
  );
}
